[package]
name = "finclip-rust-myplugin"
version = "0.1.0"
edition = "2021"

[lib]
name = "myplugin"
# this is needed to build for iOS and Android.
crate-type = ["staticlib", "lib"]

[dependencies]
once_cell = "1.10.0"
serde_json = "1.0.81"
